#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Overview | Centre for STEM Development
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/tldr/chenla-csd/csd.org
:Created:   2017-07-03T17:59@Prek Leap (11.642600N-104.919210W)
:ID:        fe0e7d73-f7c0-42d9-a114-8585d997352a
:VER:       552351650.940266635
:GEO:       48P-491193-1287029-15
:BXID:      proj:UVS0-0235
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction

** the third stage of globalization

flat vs spikey -- 

before the agricultural revolution, people were global,
moving from place to place following the food, where it grew
or grazed.  The agrigricultural revolution localized man, to
establish cities and grow food along a handful of river
valleys where the rains brought silt each year so that the
soil didn't become exhausted.

There was trade between cities and civilizations but it was
very expensive and low volume.   This was because it was
expensive to move goods, information and people.

The invention of steam engines transformed the planet,
making it cheap to move good globally using steam powered
ships and inland via steam locomotives.  This made moving
good cheap, but moving information and people was
expensive.  A handful of countries, in the North, which are
still known as the G7 were the biggest winners and the older
centers of civlization including the middle east and China,
fall into a protracted decline.  The two World Wars
reorganized the world along these new lines that remained in
place until the second stage of globalization begin in 1990.

ICT advances in information processing, and digital networks
reached a tippig point in 1990 after which information
became cheap, and to all practical purposes free, to move
anywhere on the planet.  Money at that point had moved from
being physical wealth in the form of precious metals, to
paper money that was backed up by precious metals.  By 1990,
the gold standard had been abandoned and money was literally
paper script that was backed up by the reputation of the
state issuing it.  Money had changed from being physical
wealth to symbolic -- this is known as fiat currency.
Moving around large amounts of paper script and converting
it at borders was replaced by the '90s by networks and money
was little more than numbers in databases.  Money had
changed from being symbolic to being pure information tokens
which could move around the planet as easily as an email.

The ICT revolution was also used to make transporation of
goods more efficient as well, which, when combined with
modal transportation (better known as shipping containers)
and palletization of goods, transformed the moving of goods
at scale to become so efficient and cheap, that
international shipping costs were considered to be a an
incidental cost that didn't need to be factored into the
cost of production.

This resulted in breaking up manufacturing processes into
multiple stages, which each stage being located where it was
most efficient to locate it.  The G7's industrial success
had dramatically raised their population's standard of
living and their wages.  Cheap transportation and
information transfer made it more cost effective to move
stages of manufacturing that required large amounts of
labour to countries where labour was cheaper than in the G7.

There were only 7 countries who benifited from this transfer
of manufacturing (list countries).  The rest of of the world
benifited from having access to a far wider variety of goods
at far cheaper prices than before, but otherwise they didnt
benifit nearly as much as the I7.

This brings us up to today, where we are at the brink of a
third revolution that will reorder the world as much if not
more fundementally as the first two stages of globalization.

In the second stage, transport of goods and information was
cheap, but moving people was still expensive.  It was
thought, even a few years ago that this was not something
that could change.  Air Travel is now cheap, but it is still
slow and expensive and it is true that this is not likely to
significantly change enough to usher in another revolution.
There was some talk of telepresence -- technologies such as
video conferencing, would become good enough to not need to
physically move people.  But while telepresence is improving
ad will be important in the future, it is doubtful that it
would have a large enough impact to trigger a third
revolution.

The solution is not to move people at all, but to make it
possible to automate the functions that people were
performing that were valuable enough that people had to be
moved around to perform these tasks.  Artificial
Intelligence and robots, combined with global cloud
processing and storage appears to be poised to do just that.
The third stage of globalization is already happening, and
could reach a tipping point as soon as 2020.

Most people are fixated with the impact of AI and robotics
on service jobs, and the fantasy of AI achieving greater
than human intelligence and becoming a threat to humanity.
The first is a side effect, that will not have the impact
that people believe it will.  The second is something that
must be watched for, and even planned for, in the unlikely
event of it happening in the SciFi scenarios we hear from
some very smart people like Steven Hawking.  As brilliant as
Hawking is a physicist, his views on AI are likely to be as
important as Einstein's view on Quantum Mechanics.  The
impact of AI will be far greater and weirder than can be
imagined today.

So what will happen after 2020?

  - I7 countries will see massive job losses as cheap labor
    is replaced by nearly fully automated factories.
    Recently a steel mill in Austria opened that had
    replaced 350 workers with an automated system that only
    required 14 people to operate.

  - Some people in G7 countries fantasize that when this
    happens the factories will move back to G7 countries.
    In come cases this will be the case, but not as much as
    they would like.  Factories were only located in G7 or
    I7 because that is where they could be most
    competitive.  But if moving goods, information and the
    replacement of people is all now cheap, a lot more
    locations on earth could now be equally as competitive.

  - Cheap energy will become an important competitive
    advantage, together with access to sea shipping ports,
    and cross border rail and road links.  So this leaves
    out the Tibetean Plateau, or Bhutan but it does open up
    a huge number of potential locations for manufacturing
    to become competitive.




** bootstrapping research and development

Perhaps the biggest challenge for a developing country is
knowledge transfer.  It's a bit of a Catch-22 -- foreign
investment that brings good professional jobs don't come
unless there are people in that country who can fill those
jobs.  But people won't train or study for those professions
unless there are jobs.  So schools don't teach advanced
topics, and students who wish to study those topics must
study abroad.  And when they graduate, they don't return
home, because there are no jobs for their specialty.  So
unless a foriegn company not only invests in that country
and brings with them people who can train people for those
jobs, nothing changes.

** cultural assumptions

There are many different types of cultures.  In addition to
the ethnic cultural and language that you grew up in, there
are many different types of sub-cultures that all of us
belong to.  Sports, for example has a large number of
different subcultures revolving around different kinds of
sports.  Each subculture has a core set of shared
terminology, stories, myths, jokes, mannerisms and
traditions that people in that subculture take for granted.

Science, Engineering and Technology is no different, they
all have their own subcultures.  When reading discussion
threads, exchanging email or attending conferences you will
be expected to know these same subcultural references, and
no one will even think to explain them to you.  Learning how
to learn how to become a member of these subcultures is an
important part of being part of the community and building a
career.  A lot of these cultural references and jokes come
from movies and television shows.  But also from knowing
different stories about important figures in their fields.
It is almost impossible to unerstand a lot of computer
science references unless one is more than passingly
familiar with all of the characters and stories in the Star
Wars series of films and the Star Trek television series and
films.  If you are in Physics or most of science in general,
many people assume you are familiar with stories about
figures like Physicist Richard Feynman or the astronomer
Carl Sagan.  It is as important to understand the history of
your field as any of the facts and information that make up
that field.  You can't understand Quantum Mechanics without
understanding Relativity which you can't understand without
knowing Newtonian Physics and Classical Mechanics, or
Galileo, and Copernicus and the challenges each had to
overcome to build apon the other.  Knowing the context and
the stories of how the great discoveries were made, make up
a lot of the cultural context of a field.  And there are no
hard boundries between fields.  To understand Claude Shannon
and Alan Turing's work in information theory, which modern
computing and communications is founded on you need to have
a basic understanding of entropy and work of James Clerk
Maxwell, and his thought experiment known as Maxwell's
Demon.

** The video/lecture trap

Because English is a second language for most people in
developing countries, they are under the impression that
everything can be learned by watching videos or attending
lectures.  Increasingly this is even how a growing number of
students in developing countries who speak and read English
as their primary language learn as well.  This is a very bad
habit, which must be corrected in order to do any serious
work in any field.

Books, technical & scientific papers, technical standards
and specifications should always be the primary means of
learning anything, and then use class lectures and videos to
clarify, and ask questions to help understand things that
were not clear in the book or paper.  There is no substitute
for reading, taking notes and mindmaps, working through
exercises, discussing with other students, colleagues and
teachers.

This is very hard work.  Even the most brilliant scientists
in the world, including any Noble Prize winner will tell you
without hesitation that this will always be difficult no
matter how long your work in your field.  Technical and
scientific papers in particular are short, but often
compress years of work by whole teams of scientists into a
few pages of very dense text.

If this is difficult for people who read English as a first
language, and attend some of the finest schools in the
world, with access to working scientists, teachers and
research libraries, then it will be far more difficult for
student in a developing country who speaks and reads english
as a second language who has no direct access to any of
these things.

** An alternative: build it and they will come

We must find ways of lowering the entry barrier so that
people can learn the skills that can attract investment an
bringing good professional jobs to developing countries.

If all you are training people to do is low level programing
for web and mobile app development, then the only work
you'll attract is low paying semi-skilled outsourcing work
from foreign companies.

Companies need to learn to develop their staff and look for
opportunities to attract more lucritive contracts.  

Colleges and Universities need to develop their own faculty
to encourage them to stay up to date in their fields, as
well as do their own research and development.  So when the
opportunity arises, schools can begin offering courses and
degrees in advanced subjects.

NGOs need to encourage this process, and work with schools
to train people who can take over from foreigners brought in
to establish projects.  This is good for the country and
good for the NGOs.

Consulates, and chambers of commerce of developing countries
need to reach out to companies, international and regional
organizations to find out what skills foreign companies are
looking for to invest.  They need to work with companies to
map out an education and training strategy that will ensure
that the people with the skills that will be needed will be
ready when needed.

Broad and deep fundamental skills are just as important as
vocational skills. It's important to have a long term game
in place that promotes basic research and development as
well as teaching skills needed by employers.  Schools and
government programs that conduct basic reasearch, even if
its being done on a modest budget will attract the smartest
students and help keep in them from moving abroad.  General
degrees in STEM programs will, in the long run, bring the
best jobs and investment to the country and lay the
foundation for establishing local companies with local
know-how which can compete with international products and
services.

In otherwords, chance favours the prepared mind.

** Skills are needed 


* Core Skills

** Introductory

 - Big Data
 - Machine Learning (Artificial Intelligence)
 - Understanding Cloud Technologies
   - Virtual Machines
   - Containers
   - Databases (NoSQL & Relational)
 - Introduction to the Web Stack
 - Introduction to the Scientific Method
 - Introduction to Robotics & Automation
 - Essential Statistics
 - Essential Mathematcs
 - Essential Logic & Critical Thinking
 - Essential Security

** Text Editors & the Shell

 - Introduction to Plain Text
 - Emacs & Vim
 - iPython/Jupyter/Org Babel
 - Bibliographic Management
 - Reference Management
 - Essential Bash Shell 
 - LaTex and Academic/Scientific Typesetting
 - Version Control
 - Essential Graphics
   - bitmaps
   - vectors
   - diagram & graph generation software

** Reproducible Research

 - Literate Programing
 - Literate Computing
 - Literate Devops
 - Open Data

** Programing Languages

 - Introduction to Programing
 - Python
 - R

** Spoken & Written Language

 - Technical English
 - Technical French | German | Spanish | Japanese | Korean |
   Japanese | Chinese

* Career Development

The idea here is not to have only one, paper or lecture that covers
each of these topics.  We will invite STEM professionals who are
respected in their fields to contribute their own essays and lecture
videos so that each topic is covered from different points of view.

 - You and Your Research (Career Planning)
 - How to Learn a New Subject
 - How to Read a Scientific or Technical Paper
 - How to Read a Book
 - How to Give a Lecture
 - How to Give a Talk at a Conference
 - How to Be on a Conference Panel
 - How to Give an Interview
 - How to Attend a Technical or Scientific Conference
 - How to Create A Personal Website for STEM Professionals 
 - How to Ask Questions
 - How to Blog & Leverage Social Media
 - How to Write & Submit Papers and the Peer Review Process
 - How to Search Online
 - How to Use a Physical Library
 - How to Apply for Grants & Funding
 - How to Establish a Lab & Research Program
 - Mastery: The Art of Practice & Rest
 - International Traveling Guide for STEM Professionals 
 - How to Make Screencasts & Podcasts

* Life Sciences 

 - Introduction to CRISPR

* Applied Sciences

 - GPS and Mapping
 - Remote Sensors
 - Drones: Remote Controlled Vehicles
 - Satellite Imaging
 - Fabrication
   - 3D Printing
   - CNC cutters & routers
 - Arduino & Raspberry Pi


